name: Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 전체 히스토리 필요

      - name: Get diff
        id: diff
        run: |
          git fetch origin main
          echo "::set-output name=diff::$(git diff origin/main)"
          echo "Git Diff Output:"
          git diff origin/main

      - name: Code Review with Gemini
        id: gemini
        uses: google-github-actions/auth@v1 # Google Cloud 인증 필요
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }} # Google Cloud 서비스 계정 키
      - run: |
            response=$(curl -s -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $(gcloud auth print-access-token)" \
              "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent" \
              -d '{
                "contents": [{
                  "parts": [{
                    "text": "다음 코드 변경 사항에 대한 코드 리뷰를 제공해주세요. 반드시 수정이 필요한 부분 최대 5개만 알려주세요:\n\n${{ steps.diff.outputs.diff }}"
                  }]
                }]
              }')
            echo "::set-output name=result::$(echo "$response" | jq -r '.candidates[0].content.parts[0].text')"
            echo "Gemini API Response:"
            echo "$response"
      - name: Post Review Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }} # issue-id를 issue-number로 변경
          body: |
            ## 코드 리뷰 결과
            ${{ steps.gemini.outputs.result }}
